"""empty message

Revision ID: bc2389c41205
Revises: 13d2f9c5d85b
Create Date: 2025-02-22 19:02:35.693555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bc2389c41205'
down_revision: Union[str, None] = '13d2f9c5d85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('updated')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('updated')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('updated')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
